---
name: Auto Assign Issues

on:
  issues:
    types: [opened]

jobs:
  assign:
    runs-on: ubuntu-latest

    steps:
    - name: Assign issue to repository owner
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: |
        # https://docs.github.com/en/github-cli
        # https://cli.github.com/manual/gh_issue
        gh issue edit  "${{ github.event.issue.number }}" --add-assignee "${{ github.repository_owner }}" --repo "${{ github.repository }}"
