---
name: Test

concurrency:
  group: ${{ github.workflow }}@${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch: null

jobs:
  test:
    runs-on: [self-hosted, "${{ github.repository }}"]

    steps:
      - run: |
          env
      - run: |
          curl myip.ipip.net
      - run: |
          curl -s -4 icanhazip.com
